### ISSUE TITLE
OTF-features

### ISSUE THREAD

**Issue by dom1n1k** [cyrealtype/Raleway#1]
Скачал ваш последний релиз и обнаружил, что перестали работать маюскульные цифры и альтернативы (в частности, буква W без разветвления).
Со шрифтами, скачанными из оригинального репозитория, это работает.
Скажите, это баг или просто не успели ещё синхронизировать?

**Comment by alexeiva** [comment]
e6683a5 понижен до пре-релиза. Кириллический релиз сейчас в работе. 
В настоящий момент самая актуальная версия здесь: https://github.com/impallari/Raleway
(без кириллического кернинга)
